# Generated by Django 4.1 on 2022-09-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=5, verbose_name="Название валюты (в боте)"
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="Валюта")),
                ("sign", models.CharField(max_length=1, verbose_name="Знак валюты")),
            ],
            options={
                "verbose_name": "Валюту",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.CreateModel(
            name="FormulaPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Текст формулы"),
                ),
            ],
            options={
                "verbose_name": "Формулу",
                "verbose_name_plural": "Формула",
            },
        ),
        migrations.CreateModel(
            name="ProductSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.BooleanField(default=True, verbose_name="Ссылка")),
                ("name", models.BooleanField(default=True, verbose_name="Название")),
                ("price", models.BooleanField(default=True, verbose_name="Цена")),
                ("discount", models.BooleanField(default=True, verbose_name="Скидка")),
                (
                    "description",
                    models.BooleanField(default=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Настройку товара",
                "verbose_name_plural": "Настройки товара",
            },
        ),
        migrations.CreateModel(
            name="SettingsUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Комиссия"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Логотип"
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Позиция лого",
                    ),
                ),
                ("signature", models.TextField(default="", verbose_name="Подпись")),
                (
                    "link",
                    models.BooleanField(default=False, verbose_name="Коротка ссылка"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.formulaprice",
                        verbose_name="Формула ценообразования",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.productsettings",
                        verbose_name="Настройки продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Общую настройку",
                "verbose_name_plural": "Общие настройки пользователей",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(verbose_name="Активен")),
                ("user_id", models.BigIntegerField(unique=True, verbose_name="UserID")),
                ("nickname", models.CharField(max_length=255, verbose_name="nickname")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "number",
                    models.CharField(max_length=255, verbose_name="Номер телефона"),
                ),
                ("email", models.CharField(max_length=355, verbose_name="Почта")),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                (
                    "count_members",
                    models.IntegerField(verbose_name="Количество помощников"),
                ),
            ],
            options={
                "verbose_name": "Зарегестрированный пользоваетель",
                "verbose_name_plural": "Зарегестрированные пользоваетели",
            },
        ),
        migrations.CreateModel(
            name="UnloadingTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название канала"),
                ),
                ("id_channel", models.BigIntegerField(verbose_name="ID Канала")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.settingsuser",
                        verbose_name="Настройки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройку товара",
                "verbose_name_plural": "Настройки товара",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название магазина"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.currency",
                        verbose_name="Валюта магазина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.CreateModel(
            name="SettingsUserShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Комиссия"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Логотип"
                    ),
                ),
                ("signature", models.TextField(default="", verbose_name="Подпись")),
                (
                    "link",
                    models.BooleanField(default=False, verbose_name="Коротка ссылка"),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.currency",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.formulaprice",
                        verbose_name="Формула ценообразования",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.productsettings",
                        verbose_name="Настройки продукта",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.shop",
                        verbose_name="Магазин",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройку магазига",
                "verbose_name_plural": "Настройки магазинов пользователей",
            },
        ),
        migrations.AddField(
            model_name="settingsuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bot_backend.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BinaryField(verbose_name="Активен")),
                ("user_id", models.BigIntegerField(verbose_name="Telegram ID")),
                (
                    "invite_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_backend.user",
                        verbose_name="Пригласивший пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Помощника",
                "verbose_name_plural": "Помощники",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("link", models.CharField(max_length=20000, verbose_name="Ссылка")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=20000, null=True, verbose_name="Описание"
                    ),
                ),
                ("cost", models.FloatField(verbose_name="Цена")),
                ("discount", models.FloatField(verbose_name="Скидка")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bot_backend.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="bot_backend.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение поста",
                "verbose_name_plural": "Изображения постов",
            },
        ),
    ]
