# Generated by Django 4.1 on 2022-08-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=355, verbose_name='Почта')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Зарегестрированный пользоваетель',
                'verbose_name_plural': 'Зарегестрированные пользоваетели',
            },
        ),
    ]
