# Generated by Django 4.1 on 2022-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.CharField(max_length=20000, verbose_name='Альбом')),
                ('description', models.CharField(max_length=20000, verbose_name='Описание')),
                ('cost', models.CharField(max_length=10, verbose_name='Цена')),
                ('over_cost', models.CharField(max_length=10, verbose_name='Надценка')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=355, verbose_name='Почта')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Зарегестрированный пользоваетель',
                'verbose_name_plural': 'Зарегестрированные пользоваетели',
            },
        ),
    ]
