# Generated by Django 4.1 on 2022-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_backend", "0003_chanel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="second_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=700, verbose_name="ФИО"),
        ),
    ]
