# Generated by Django 4.1 on 2022-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_backend', '0004_remove_user_city_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=7000, verbose_name='ФИО'),
        ),
    ]
